# Generated by Django 4.1.7 on 2023-04-28 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='intro',
            new_name='title',
        ),
    ]
