# Generated by Django 3.2.12 on 2023-05-01 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
